Exercise: Matrix Border Su m

Goal: Given a 2D NumPy array of integers, return the sum of all the numbers located on the border (first row, last row, first column, last column).

In [2]:
import numpy as np

In [3]:
matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13,14, 15, 16]
])

In [5]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
print(matrix[:,0])
print(matrix[0,:])
print(matrix[0,:]+matrix[:,0])

[ 1  5  9 13]
[1 2 3 4]
[ 2  7 12 17]


In [ ]:
def border_sum(matrix):
    pass